name: Generate Documents

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  convert_docs:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4

        - name: Markdown to PDF and HTML
          uses: BaileyJM02/markdown-to-pdf@v1.2.0
          with:
            input_path: MData/ # Folder where your .md files are
            output_dir: afiles/ # Where to save the results
            build_html: true # Also generate HTML
            build_pdf: true # Also generate PDF
            table_of_contents: false

        - name: Commit Files
          run: |
            git config --local user.email "269244147+felipefinch@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git add afiles/
            git commit -m "Distributing converted MD (PDF/HTML) Files to 'afiles' folder in repository." || echo "No changes to commit"
            git push
            
        # NO ARTIFACTS
        # - name: Upload Artifacts
        #   uses: actions/upload-artifact@v4
        #   with:
        #     name: converted-documents
        #     path: afacts/
